"""Update Reservation model

Revision ID: 1932d1816dbb
Revises: 8a02e178fd18
Create Date: 2016-01-12 13:09:41.079367

"""

# revision identifiers, used by Alembic.
revision = '1932d1816dbb'
down_revision = '8a02e178fd18'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Reservations', sa.Column('paid', sa.Integer(), nullable=True))
    op.add_column('Reservations', sa.Column('reason', sa.String(300), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Reservations', 'reason')
    op.drop_column('Reservations', 'paid')
    ### end Alembic commands ###
