"""Add HTML description for resource

Revision ID: 334ec465acec
Revises: 6fa3823b89a8
Create Date: 2016-01-06 21:09:10.972700

"""

# revision identifiers, used by Alembic.
revision = '334ec465acec'
down_revision = '6fa3823b89a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Resources', sa.Column('description_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Resources', 'description_html')
    ### end Alembic commands ###
