"""Add operator to payment

Revision ID: 67067678292b
Revises: 9f9b36758e55
Create Date: 2016-01-24 20:43:00.542081

"""

# revision identifiers, used by Alembic.
revision = '67067678292b'
down_revision = '9f9b36758e55'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Payments', sa.Column('operator_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_foreign_key(None, 'Payments', 'Users', ['operator_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Payments', type_='foreignkey')
    op.drop_column('Payments', 'operator_id')
    ### end Alembic commands ###
