"""Add user photo

Revision ID: 8a02e178fd18
Revises: e01c063dd5cb
Create Date: 2016-01-11 19:52:25.205537

"""

# revision identifiers, used by Alembic.
revision = '8a02e178fd18'
down_revision = 'e01c063dd5cb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('photo_filename', sa.String(length=100), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'photo_filename')
    ### end Alembic commands ###
