"""Change int to float in ExpenseNote

Revision ID: a75e730b7c9d
Revises: 47172e76faa4
Create Date: 2016-05-31 21:16:50.938424

"""

# revision identifiers, used by Alembic.
revision = 'a75e730b7c9d'
down_revision = '47172e76faa4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ExpenseNotes', 'total',
               existing_type=mysql.INTEGER(display_width=11), type_=mysql.FLOAT(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ExpenseNotes', 'total',
               type_=mysql.INTEGER(display_width=11), existing_type=mysql.FLOAT(),
               nullable=False)
    ### end Alembic commands ###
