"""Update Reservation model

Revision ID: b51909f47d3a
Revises: 67067678292b
Create Date: 2016-01-25 18:09:22.375149

"""

# revision identifiers, used by Alembic.
revision = 'b51909f47d3a'
down_revision = '67067678292b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Reservations', 'paid')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Reservations', sa.Column('paid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
