"""Add paid to ExpenseNote

Revision ID: d6a8cb43919a
Revises: df20b2409953
Create Date: 2016-07-05 15:51:43.653293

"""

# revision identifiers, used by Alembic.
revision = 'd6a8cb43919a'
down_revision = 'df20b2409953'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ExpenseNotes', sa.Column('paid', sa.Boolean(), nullable=False))
    op.alter_column('PaymentDescriptions', 'type',
               existing_type=mysql.ENUM('reservation', 'membership', 'custom', 'credits'),
               nullable=False)
    op.alter_column('Payments', 'method',
               existing_type=mysql.ENUM('terminal', 'cash', 'online', 'credits'),
               nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Payments', 'method',
               existing_type=mysql.ENUM('terminal', 'cash', 'online', 'credits'),
               nullable=True)
    op.alter_column('PaymentDescriptions', 'type',
               existing_type=mysql.ENUM('reservation', 'membership', 'custom', 'credits'),
               nullable=True)
    op.drop_column('ExpenseNotes', 'paid')
    ### end Alembic commands ###
