"""Add Reservation and Available models

Revision ID: e01c063dd5cb
Revises: 2f10abff473c
Create Date: 2016-01-10 19:48:39.701692

"""

# revision identifiers, used by Alembic.
revision = 'e01c063dd5cb'
down_revision = '2f10abff473c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['Resources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Availability_resource_id'), 'Availability', ['resource_id'], unique=False)
    op.create_index(op.f('ix_Availability_user_id'), 'Availability', ['user_id'], unique=False)
    op.create_table('Reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['Resources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Reservations_resource_id'), 'Reservations', ['resource_id'], unique=False)
    op.create_index(op.f('ix_Reservations_user_id'), 'Reservations', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Reservations_user_id'), table_name='Reservations')
    op.drop_index(op.f('ix_Reservations_resource_id'), table_name='Reservations')
    op.drop_table('Reservations')
    op.drop_index(op.f('ix_Availability_user_id'), table_name='Availability')
    op.drop_index(op.f('ix_Availability_resource_id'), table_name='Availability')
    op.drop_table('Availability')
    ### end Alembic commands ###
