"""Add expense note

Revision ID: fa71f17f3182
Revises: 280a9c835af7
Create Date: 2016-03-14 21:50:27.756661

"""

# revision identifiers, used by Alembic.
revision = 'fa71f17f3182'
down_revision = '280a9c835af7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ExpenseNotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('bank_account', sa.String(length=50), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('date_requested', sa.Date(), nullable=True),
    sa.Column('filename', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ExpenseNotes')
    ### end Alembic commands ###
