"""Add resources

Revision ID: 0c30600413ab
Revises: b7b3300194d8
Create Date: 2015-12-30 16:54:13.817051

"""

# revision identifiers, used by Alembic.
revision = '0c30600413ab'
down_revision = 'b7b3300194d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('price_p_per', sa.Integer(), nullable=True),
    sa.Column('reserv_per', sa.Integer(), nullable=True),
    sa.Column('cons_name', sa.String(length=64), nullable=True),
    sa.Column('cons_cost', sa.Integer(), nullable=True),
    sa.Column('cons_unit', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Resources')
    ### end Alembic commands ###
