"""Add settings

Revision ID: 280a9c835af7
Revises: b0ad3831068d
Create Date: 2016-03-05 19:47:52.884540

"""

# revision identifiers, used by Alembic.
revision = '280a9c835af7'
down_revision = 'b0ad3831068d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Settings',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Settings')
    ### end Alembic commands ###
