"""Update Payment with paid

Revision ID: 2a2811c50158
Revises: 7f59125777ef
Create Date: 2016-02-24 13:28:54.541086

"""

# revision identifiers, used by Alembic.
revision = '2a2811c50158'
down_revision = '7f59125777ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Payments', sa.Column('paid', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Payments', 'paid')
    ### end Alembic commands ###
