"""Add skills to resources

Revision ID: 2f10abff473c
Revises: 334ec465acec
Create Date: 2016-01-06 21:41:03.845196

"""

# revision identifiers, used by Alembic.
revision = '2f10abff473c'
down_revision = '334ec465acec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SkillsResources',
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['Resources.id'], ),
    sa.ForeignKeyConstraint(['skill_id'], ['Skills.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SkillsResources')
    ### end Alembic commands ###
