"""Add consumption

Revision ID: 58c32b0d298f
Revises: d6a8cb43919a
Create Date: 2016-07-18 19:16:46.661655

"""

# revision identifiers, used by Alembic.
revision = '58c32b0d298f'
down_revision = 'd6a8cb43919a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("PaymentDescriptions", "type", existing_type=sa.Enum(u'reservation', u'membership', u'custom', u'credits'),
                    type_=sa.Enum(u'reservation', u'membership', u'custom', u'credits', u'consumption'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('PaymentDescriptions', 'type',
               existing_type=mysql.ENUM(u'reservation', u'membership', u'custom', u'credits', u'consumption'),
               type_=sa.Enum(u'reservation', u'membership', u'custom', u'credits'), nullable=False)
    ### end Alembic commands ###
