"""Add user location and about_me

Revision ID: 996571a4bd56
Revises: 635daab782d8
Create Date: 2015-12-28 17:19:55.823840

"""

# revision identifiers, used by Alembic.
revision = '996571a4bd56'
down_revision = '635daab782d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('Users', sa.Column('location', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'location')
    op.drop_column('Users', 'about_me')
    ### end Alembic commands ###
