"""Add skill_required

Revision ID: 9af67367cf5a
Revises: c50e32787023
Create Date: 2018-06-11 20:13:20.520742

"""

# revision identifiers, used by Alembic.
revision = '9af67367cf5a'
down_revision = 'c50e32787023'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('junk')
    op.add_column('Resources', sa.Column('skill_required', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'UserSkills', 'Users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'UserSkills', 'Skills', ['skill_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'UserSkills', type_='foreignkey')
    op.drop_constraint(None, 'UserSkills', type_='foreignkey')
    op.drop_column('Resources', 'skill_required')
    op.create_table('junk',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('skill_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], [u'Skills.id'], name=u'junk_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'Users.id'], name=u'junk_ibfk_2'),
    mysql_default_charset=u'latin1',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
