"""Remove duplicate info from payments

Revision ID: 9f9b36758e55
Revises: f7508405b6ec
Create Date: 2016-01-24 20:08:16.570718

"""

# revision identifiers, used by Alembic.
revision = '9f9b36758e55'
down_revision = 'f7508405b6ec'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Payments_type', table_name='Payments')
    op.drop_constraint(u'Payments_ibfk_1', 'Payments', type_='foreignkey')
    op.drop_column('Payments', 'reservation_id')
    op.drop_column('Payments', 'type')
    op.drop_column('Payments', 'description')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Payments', sa.Column('description', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('Payments', sa.Column('type', mysql.ENUM(u'membership', u'reservation', u'consumable', u'event', u'custom'), nullable=False))
    op.add_column('Payments', sa.Column('reservation_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'Payments_ibfk_1', 'Payments', 'Reservations', ['reservation_id'], ['id'])
    op.create_index('ix_Payments_type', 'Payments', ['type'], unique=False)
    ### end Alembic commands ###
