"""Add skills

Revision ID: b7b3300194d8
Revises: 996571a4bd56
Create Date: 2015-12-29 16:10:14.616130

"""

# revision identifiers, used by Alembic.
revision = 'b7b3300194d8'
down_revision = '996571a4bd56'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('UserSkills',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['Skills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserSkills')
    op.drop_table('Skills')
    ### end Alembic commands ###
