"""Add Locks

Revision ID: c50e32787023
Revises: 58c32b0d298f
Create Date: 2017-10-09 18:56:55.244951

"""

# revision identifiers, used by Alembic.
revision = 'c50e32787023'
down_revision = '58c32b0d298f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('UserLocks',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lock_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lock_id'], ['Locks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], )
    )
    op.alter_column(u'PaymentDescriptions', 'type',
               existing_type=mysql.ENUM(u'reservation', u'membership', u'custom', u'credits', u'consumption'),
               nullable=False)
    op.add_column(u'Users', sa.Column('keycard', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'Users', 'keycard')
    op.alter_column(u'PaymentDescriptions', 'type',
               existing_type=mysql.ENUM(u'reservation', u'membership', u'custom', u'credits', u'consumption'),
               nullable=True)
    op.drop_table('UserLocks')
    op.drop_table('Locks')
    ### end Alembic commands ###
