"""Add cost column to Reservation

Revision ID: c7aa1b4ff40c
Revises: 1c04b620686d
Create Date: 2016-01-20 16:55:02.124909

"""

# revision identifiers, used by Alembic.
revision = 'c7aa1b4ff40c'
down_revision = '1c04b620686d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Reservations', sa.Column('cost', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Reservations', 'cost')
    ### end Alembic commands ###
