"""Add credits

Revision ID: df20b2409953
Revises: a75e730b7c9d
Create Date: 2016-06-13 15:50:01.112059

"""

# revision identifiers, used by Alembic.
revision = 'df20b2409953'
down_revision = 'a75e730b7c9d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CreditHistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['Users.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['Payments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('ExpenseNotes', 'total',
               existing_type=mysql.FLOAT(),
               nullable=False)

    op.add_column('Users', sa.Column('credits', sa.Float(), nullable=False))

    op.alter_column("Payments", "method", existing_type=sa.Enum('terminal', 'cash', 'online'),
                    type_=sa.Enum('terminal', 'cash', 'online', 'credits'))

    op.alter_column("PaymentDescriptions", "type", existing_type=sa.Enum('reservation', 'membership', 'custom'),
                    type_=sa.Enum('reservation', 'membership', 'custom', 'credits'))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'credits')

    op.alter_column('ExpenseNotes', 'total',
               existing_type=mysql.FLOAT(),
               nullable=True)

    op.drop_table('CreditHistory')

    op.alter_column("Payments", "method", existing_type=sa.Enum('terminal', 'cash', 'online', 'credits'),
                    type_=sa.Enum('terminal', 'cash', 'online'))

    op.alter_column("PaymentDescriptions", "type", existing_type=sa.Enum('reservation', 'membership', 'custom', 'credits'),
                    type_=sa.Enum('reservation', 'membership', 'custom'))

    ### end Alembic commands ###
