"""Add payments

Revision ID: e8e00d6a0ee6
Revises: a85c9739c9f5
Create Date: 2016-01-18 21:05:41.408613

"""

# revision identifiers, used by Alembic.
revision = 'e8e00d6a0ee6'
down_revision = 'a85c9739c9f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('type', sa.Enum(u'membership', u'reservation', u'consumable', u'event', u'custom'), nullable=False),
    sa.Column('method', sa.Enum(u'terminal', u'cash', u'online'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reservation_id'], ['Reservations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Payments_type'), 'Payments', ['type'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Payments_type'), table_name='Payments')
    op.drop_table('Payments')
    ### end Alembic commands ###
