"""Update payments

Revision ID: f7508405b6ec
Revises: c7aa1b4ff40c
Create Date: 2016-01-23 17:27:18.577532

"""

# revision identifiers, used by Alembic.
revision = 'f7508405b6ec'
down_revision = 'c7aa1b4ff40c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('PaymentDescriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum(u'reservation', u'membership', u'custom'), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['Payments.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['Reservations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_PaymentDescriptions_type'), 'PaymentDescriptions', ['type'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_PaymentDescriptions_type'), table_name='PaymentDescriptions')
    op.drop_table('PaymentDescriptions')
    ### end Alembic commands ###
